---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apr
      name: apr
      namespace: default
    spec:
      containers:
      - name: apr
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/apr:4df6fdfad3ee67f0b1c604cf42d4d54e21c6c5a9
        env:
        - name: PORT
          value: "4000"
        - name: MIX_ENV
          value: prod
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apr
  name: apr
  namespace: default
spec:
  ports:
  - port: 80
    nodePort: 30101
    protocol: TCP
  selector:
    app: apr
  sessionAffinity: None
  type: NodePort
