apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: apr
  name: apr-config
data:
  MIX_ENV: prod
  APR_HOST: apr-staging.artsy.net
  RABBITMQ_HOST: rmq-amqp
  RABBITMQ_USER: apr
  RABBITMQ_PORT: "5672"
